### ISSUE TITLE
IMU

### ISSUE THREAD

**Issue by vintheruler1** [berndporr/pyFirmata2#11]
Is there any way to access the IMU that is built into the Arduino Nano 33 IOT?

**Comment by berndporr** [comment]
Looks like that not even firmata supports it. PyFirmata is really just for the standard digital I/O and analogue in.

**Comment by vintheruler1** [comment]
> Looks like that not even firmata supports it. PyFirmata is really just for the standard digital I/O and analogue in.

Ah alright. Do you by chance know any other libraries that could support it? I know that Firmata would work if the IMU was plugged into the ports.

**Comment by berndporr** [comment]
Sorry. No idea. I don't have that device. I only maintain the library for my teaching and for that it's just measuring voltage.

**Comment by vintheruler1** [comment]
Alright, thanks for the help.
