### ISSUE TITLE
Arduino serial TX hangs

### ISSUE THREAD

**Issue by kdickie59** [berndporr/pyFirmata2#14]
when running the standardfirmata sketch on an Arduino mega and running the  standard print_analog_data example on a raspberry pi 4 the Arduino TX light remains on solid after the 10 seconds and the exit() function.

**Comment by kdickie59** [comment]
solution:
We need to stop the Arduino from talking before we close com on our end.  simply add:
self.board.analog[0].disable_reporting()
to the stop function before we "exit()".

**Comment by berndporr** [comment]
Can you try it out? I have only an RPI5 and Uno.
