### ISSUE TITLE
Pyfirmata 2 AUTODETECT only returns none

### ISSUE THREAD

**Issue by AlboProgrammer** [berndporr/pyFirmata2#17]
Im new in programming with pyfirmata 2.
I have a Arduino Uno and want to controll it python.
Because we have diffrent computer and the Arduino has always a other Port we wanted that the Program to auto detect the right Port.
We can find the Adress from the arduino but the Programm gives us none back. What can I do?

![Screenshot 2024-06-04 133110](https://github.com/berndporr/pyFirmata2/assets/171685741/e2566310-86cd-4d8a-816a-94402feace87)

I comment the part out because to test the other things.
I am Programming on Windows with Python 3.12

**Comment by berndporr** [comment]
AUTODETECT is a constant (none):
https://github.com/berndporr/pyFirmata2/blob/master/pyfirmata2/pyfirmata2.py#L92
it makes the constructor to detect it. If successful then all good. If not it throws an exception.

**Comment by AlboProgrammer** [comment]
yeah, but this is what i become when i try run the programm:
<img width="231" alt="Error" src="https://github.com/berndporr/pyFirmata2/assets/171685741/ca1fc859-58ab-42f8-bbe4-82844e68feb0">
when i do to find the comport myself , this i got in return:
<img width="460" alt="Port" src="https://github.com/berndporr/pyFirmata2/assets/171685741/b996b117-6f49-4f2e-8901-df633f7d6986">

**Comment by berndporr** [comment]
https://github.com/berndporr/pyFirmata2/blob/master/pyfirmata2/pyfirmata2.py#L106
it's not using _any_ com port but only those which have the word "USB" in it as com ports are also used for other purposes. Perhaps your computer has a different description than "USB"? Can you check what description it returns? It could also be that you have either a newer or older version of pyserial which just returns something different for the description. If pyserial is very old then description might be blank. Just put a print statement in there and see what description gives you and report back. Thanks.

**Comment by AlboProgrammer** [comment]
I saw you changed the pyfirmata2 Libary for the windows part. 
I downloaded it and start the programm again. Now it come this in return:
![image](https://github.com/berndporr/pyFirmata2/assets/171685741/5bb7ff7e-ff3e-440b-9edc-e67be3ece357)
I have pyserial 3.5 and i am asking, how do i get the devices description as print in return

**Comment by berndporr** [comment]
I would like to know what d.description contains in your case:
https://github.com/berndporr/pyFirmata2/blob/master/pyfirmata2/pyfirmata2.py#L106
Or just add a print(l) here:
https://github.com/berndporr/pyFirmata2/blob/master/pyfirmata2/pyfirmata2.py#L96
and tell me.

**Comment by berndporr** [comment]
Even simpler. Run this:https://github.com/berndporr/pyFirmata2/blob/master/examples/scan.py

**Comment by AlboProgrammer** [comment]
I ran the scan.py and this i got in return:
![scan py](https://github.com/berndporr/pyFirmata2/assets/171685741/ed796b9b-ebc1-441b-b19f-6e8d350a767e)

**Comment by berndporr** [comment]
thanks. I've just added "Arduino" as a valid description. If you check out the newest version it should detect the COM port. Can you try?

**Comment by berndporr** [comment]
https://github.com/berndporr/pyFirmata2/commit/967da5a2c3ab09ca649c8fece3bb52a278d69131 it's here. Feel free to play around with it. Not at a computer with an Arduino so cannot check.

**Comment by AlboProgrammer** [comment]
Thank you, its now working. Have a nice day

**Comment by berndporr** [comment]
:)
