### ISSUE TITLE
HC-SR04 supported? PulseIN available?

### ISSUE THREAD

**Issue by Kakcalu13** [berndporr/pyFirmata2#2]
Hi,

I was trying to connect to python3 with arduino UNO using pyfirmata2 library. 

Is there any way to use HC-SR04 or at least, PulseIN? 

In arduino,
to use PulseIN is like 
`duration = pulseIn(echoPin, HIGH);`

Is there a way to do it through pyFirmata2?

Thank you so much for your time! Love this library so far!

**Comment by berndporr** [comment]
This library focusses on the analogue pins and sampling them at a precise rate. There are no plans to expand it to the digital pins.
