### ISSUE TITLE
Minimum sampling rate?

### ISSUE THREAD

**Issue by omersayli** [berndporr/pyFirmata2#3]
I would like to ask, in pyFirmata2 minimum sampling rate is stated to be 10 ms (100Hz). Is it fixed for all Arduino cards (there are advanced versions)?

**Comment by berndporr** [comment]
You mean above 100Hz, so for example 1kHz? That's not possible as the USB protocol used is too crude for higher rates. If you are using it under Linux then you can make one of the USB-DUX sigmas yourse;f: https://github.com/glasgowneuro/usbdux which I sold till recently but now open hardware.

**Comment by omersayli** [comment]
Thanks for the fast reply (I also asked the same question on Twitter, you may omit that). Yes, I meant higher sampling frequencies than 100 Hz. I have Arduino Duo, I will try it and inform you, maybe I can get higher sampling rate
