### ISSUE TITLE
Is pyFirmata ready for Apple M1 MAC? 

### ISSUE THREAD

**Issue by 54WC** [berndporr/pyFirmata2#4]
I run pyFirmata2 with Arduino on Apple M1 MAC. I follow the every instruction to install pyFirmata2. It looks good, no error happens. But it just have no effect to blink a LED on pin 13, or just receive "none" from analog pin 0.  Actually, the pyFirmata suffer the same issue.  Do you experience the same situation? 
Some information for reference. 
Arduino 2.0.0 Belta 4
Python 3.9.2
mac Bgi sur 11.4

information from installation: 
running install
running bdist_egg
running egg_info
writing pyFirmata2.egg-info/PKG-INFO
writing dependency_links to pyFirmata2.egg-info/dependency_links.txt
writing requirements to pyFirmata2.egg-info/requires.txt
writing top-level names to pyFirmata2.egg-info/top_level.txt
reading manifest file 'pyFirmata2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
writing manifest file 'pyFirmata2.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-11-x86_64/egg
creating build/bdist.macosx-11-x86_64/egg/pyfirmata2
copying build/lib/pyfirmata2/util.py -> build/bdist.macosx-11-x86_64/egg/pyfirmata2
copying build/lib/pyfirmata2/__init__.py -> build/bdist.macosx-11-x86_64/egg/pyfirmata2
copying build/lib/pyfirmata2/mockup.py -> build/bdist.macosx-11-x86_64/egg/pyfirmata2
copying build/lib/pyfirmata2/pyfirmata2.py -> build/bdist.macosx-11-x86_64/egg/pyfirmata2
copying build/lib/pyfirmata2/boards.py -> build/bdist.macosx-11-x86_64/egg/pyfirmata2
byte-compiling build/bdist.macosx-11-x86_64/egg/pyfirmata2/util.py to util.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/pyfirmata2/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/pyfirmata2/mockup.py to mockup.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/pyfirmata2/pyfirmata2.py to pyfirmata2.cpython-39.pyc
byte-compiling build/bdist.macosx-11-x86_64/egg/pyfirmata2/boards.py to boards.cpython-39.pyc
creating build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/PKG-INFO -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/SOURCES.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/dependency_links.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/not-zip-safe -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/requires.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
copying pyFirmata2.egg-info/top_level.txt -> build/bdist.macosx-11-x86_64/egg/EGG-INFO
creating 'dist/pyFirmata2-2.1.1-py3.9.egg' and adding 'build/bdist.macosx-11-x86_64/egg' to it
removing 'build/bdist.macosx-11-x86_64/egg' (and everything under it)
Processing pyFirmata2-2.1.1-py3.9.egg
removing '/usr/local/lib/python3.9/site-packages/pyFirmata2-2.1.1-py3.9.egg' (and everything under it)
creating /usr/local/lib/python3.9/site-packages/pyFirmata2-2.1.1-py3.9.egg
Extracting pyFirmata2-2.1.1-py3.9.egg to /usr/local/lib/python3.9/site-packages
pyFirmata2 2.1.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.9/site-packages/pyFirmata2-2.1.1-py3.9.egg
Processing dependencies for pyFirmata2==2.1.1
Searching for pyserial==3.5
Best match: pyserial 3.5
Adding pyserial 3.5 to easy-install.pth file
Installing pyserial-miniterm script to /usr/local/bin
Installing pyserial-ports script to /usr/local/bin

Using /usr/local/lib/python3.9/site-packages
Finished processing dependencies for pyFirmata2==2.1.1

**Comment by omersayli** [comment]
As far as I know, there are issues with M1 Macs for Python. It is relatively new as you know (check this for Anaconda's statement [https://www.anaconda.com/blog/apple-silicon-transition](https://www.anaconda.com/blog/apple-silicon-transition) )

**Comment by berndporr** [comment]
Did you upload firmata to your Arduino with the Arduino IDE?
https://github.com/berndporr/pyFirmata2#upload-firmata

Which test program did you try to flash the LED? The demo from this repo?

**Comment by 54WC** [comment]
> Did you upload firmata to your Arduino with the Arduino IDE?
> https://github.com/berndporr/pyFirmata2#upload-firmata
> 
> Which test program did you try to flash the LED? The demo from this repo?

Thank you very much. I make a mistakes which only includes firmata.h in the sketch.  It works when standardfirmata is uploaded.(follow the instruction exactly. )
