### ISSUE TITLE
How to use an analog pin as an output?

### ISSUE THREAD

**Issue by davthedev** [berndporr/pyFirmata2#9]
I am using this library to control an already-build Firmata project. It was used before using a different software for control.

Analog pins of the Arduino Uno are used as digital outputs to light up LEDs.
So far, I was not able to light up any of those using pyFirmata2. It worked using firmata.js.

My attempts are as follows. I tried all the analog pins with the same result.

```
analog_out_0 = board.get_pin('a:0:o')
analog_out_0.write(to_write)
```
Gives an error: Analog pin 0 is set up as an INPUT and can therefore not be written to

```
analog_out_0 = board.get_pin('a:0:o')
analog_out_0.mode = pyfirmata2.OUTPUT
analog_out_0.write(to_write)
```
No error but does not work.

Using firmata.js, I could address the analog pins the same way as digital ones  using the indexes 14 (for analog pin 0) and above.

Is it supported by pyfirmata2, or is there a mistake in my approach?

**Comment by berndporr** [comment]
The arduino has no analogue output pins as it hasn't got any digital to analogue converter. It has only _digital_ outputs.
```
digital_out_3 = board.get_pin('d:3:o')
digital_out_3.write(True)
```
Or you use PWM.

**Comment by davthedev** [comment]
The way I named my variables may have caused confusion.
I would like to use the analog pins as _digital_ outputs to light up LEDs at the maximum level or turn them off. No need to do PWM at all.

I am porting the software from NodeJS to Python to control the hardware project, hence my comparison with firmata.js. The hardware is already set with a custom PCB that plugs into the Arduino like a shield. I cannot change the pin assignment.

Firmata supports it. For example, some libraries like firmata.js allows you to address the analog pin 0 as "digital 14" for all-or-nothing output and so on, once you set the pin mode to output. This is how I was able to light up the LEDs on pins A0...A5 of the Arduino Uno.

I thought it is a limitation of the pyFirmata2 library. Seems that it is confirmed in the original pyFirmata: https://github.com/tino/pyFirmata/issues/31

Perhaps I will have to understand the low-level protocol and bit-bang the serial port for those specific actions.

**Comment by berndporr** [comment]
"I would like to use the analog pins as digital outputs to light up LEDs."
An analogue pin by definition is one which is driven by an digital to analogue converter. The Arduino has no DAC. Ergo it has no analogue output pins. Just because other front-ends mix the meaning of digital and analogue doesn't mean that I need to get into this mess as well an I won't. End of story.

**Comment by berndporr** [comment]
I've read the Tino's comment about it and same here: I won't implement it, I have not time to do it and it's a good thing to keep the nomenclature clean between analogue and digital. After all the Arduino is a device for teaching and training. Phrases like "I would like to use the analog pins as digital outputs." do not make sense by mixing the meaning of analogue and digital. I'm sure internally the ARM processor can be configured to anything on any pin but the Arduino designers have designated these pins as analogue input pins and that's how they are labelled.
